#!/bin/bash
imagename="rothgar/microbot"
if [ $# -eq 0 ];then
 tagver="latest"
else
 tagver="${1}"
fi
echo "Now building: ${imagename}:${tagver}"
docker buildx build --platform linux/amd64,linux/arm64 --rm=true --no-cache=true --pull=true -t ${imagename}:${tagver} --push .
#docker push ${imagename}:${tagver}
