#!/bin/bash
imagename="rothgar/microbot"
if [ $# -eq 0 ];then
 tagver="latest"
else
 tagver="${1}"
fi

echo "Now building: ${imagename}:${tagver}"
docker build --rm --no-cache --pull -t ${imagename}:${tagver} .
docker push ${imagename}:${tagver}
